import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                'resources/js/auth.js',
                'resources/js/dashboard.js',
                'resources/js/companies.js',
                'resources/js/companies-index.js',
                'resources/js/company-show.js',
                'resources/js/profile.js',
                'resources/js/change-password.js',
                'resources/js/departments-index.js',
                'resources/js/departments.js',
                'resources/js/documents-index.js',
                'resources/js/documents.js',
                'resources/js/assets-index.js',
                'resources/js/assets.js',
                'resources/js/shifts-index.js',
                'resources/js/shifts.js',
                'resources/js/roles-index.js',
                'resources/js/roles-show.js',
                'resources/js/people.js',
                'resources/js/employees-index.js',
                'resources/js/employee-profile.js',
                'resources/js/employees.js',
                'resources/js/attendance.js',
                'resources/js/attendance-today.js',
                'resources/js/attendance-punch.js',
                'resources/js/attendance-regularize.js',
                'resources/js/holidays-index.js',
                'resources/js/holidays.js',
                'resources/js/weekly-off.js',
                'resources/js/portal-start.js',
                'resources/js/leave-types-index.js',
                'resources/js/leave-types.js',
                'resources/js/leaves-index.js',
                'resources/js/leaves-apply.js',
                'resources/js/leaves-show.js',
                'resources/js/leaves-balances.js',
                'resources/js/leaves-manage-balances.js',
                'resources/js/payroll.js',
            ],
            refresh: true,
        }),
    ],
});
