<?php

return [
    'gallery_tabs' => [
        ['key' => 'leave', 'label' => 'Leave'],
        ['key' => 'attendance', 'label' => 'Attendance'],
        ['key' => 'people', 'label' => 'People'],
        ['key' => 'salary', 'label' => 'Salary'],
        ['key' => 'expense', 'label' => 'Expense'],
    ],

    'recommended' => [
        'head_count_by_department',
        'employees_joined_by_month_by_gender',
        'gender_breakdown',
    ],

    'recommended_by_role' => [
        'employee' => [
            'my_attendance_overview',
            'my_leave_by_status',
            'my_hours_by_date',
        ],
        'team_lead' => [
            'team_attendance_overview',
            'team_leave_by_status',
            'team_hours_by_person',
        ],
        'department_head' => [
            'team_attendance_overview',
            'team_leave_by_status',
            'team_hours_by_person',
        ],
    ],

    'default_widgets' => [
        'head_count_by_department',
        'gender_breakdown',
        'attendance_status',
        'leave_balance_by_department',
        'approved_expenses_by_department',
    ],

    'default_widgets_by_role' => [
        'employee' => [
            'my_attendance_overview',
            'my_leave_by_status',
            'my_hours_by_date',
            'my_expense_by_status',
            'my_regularization_by_status',
        ],
        'team_lead' => [
            'team_attendance_overview',
            'team_leave_by_status',
            'team_hours_by_person',
            'team_attendance_trend',
            'team_pending_approvals',
            'team_regularization_by_employee',
        ],
        'department_head' => [
            'team_attendance_overview',
            'team_leave_by_status',
            'team_hours_by_person',
            'team_attendance_trend',
            'team_pending_approvals',
        ],
    ],

    /*
    | chart_type: bar|donut|line (Chart.js renderer)
    | chart_type_label: display badge in gallery (Histogram, Pie Chart, etc.)
    */
    'widgets' => [
        // People
        'head_count_by_department' => [
            'label' => 'Head Count By Department',
            'description' => 'Active employee headcount grouped by department',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
        ],
        'head_count_by_designation' => [
            'label' => 'Head Count By Designation',
            'description' => 'Active employee headcount grouped by designation',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
        ],
        'head_count_by_work_location' => [
            'label' => 'Head Count By Work Location',
            'description' => 'Active employee headcount grouped by work location (city)',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
        ],
        'employees_joined_by_month' => [
            'label' => 'Employees Joined By Month',
            'description' => 'New joiners in the selected period grouped by month',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'employees_joined_by_month_by_gender' => [
            'label' => 'Employees Joined By Month By Gender',
            'description' => 'New joiners by month and gender for the selected period',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'gender_breakdown' => [
            'label' => 'Gender Breakdown',
            'description' => 'Active employees grouped by gender',
            'category' => 'people',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
        ],
        'tenure_distribution_by_department' => [
            'label' => 'Tenure Distribution by Department',
            'description' => 'Average tenure in years by department',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Box Plot',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
        ],
        'tenure_distribution_by_work_location' => [
            'label' => 'Tenure Distribution by Work Location',
            'description' => 'Average tenure in years by work location',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Box Plot',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
        ],
        'employee_length_of_service_distribution' => [
            'label' => 'Employee Length of Service Distribution',
            'description' => 'Employee count by years of service bands',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
        ],
        'age_vs_designation_with_tenure' => [
            'label' => 'Age vs Designation with Tenure',
            'description' => 'Average age by designation',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Scatter Plot',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
        ],
        'age_vs_tenure_by_department' => [
            'label' => 'Age vs Tenure by Department',
            'description' => 'Average age and tenure by department',
            'category' => 'people',
            'chart_type' => 'bar',
            'chart_type_label' => 'Scatter Plot',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
        ],

        // Leave
        'leave_balance_by_department' => [
            'label' => 'Employee-Policy Distribution of Leave Balance Changes by Department',
            'description' => 'Leave balance change totals grouped by department',
            'category' => 'leave',
            'chart_type' => 'bar',
            'chart_type_label' => 'Bar Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'leave_balance_by_dept_policy_designation' => [
            'label' => 'Leave Balance Change by Department, Policy, and Designation',
            'description' => 'Leave balance changes across department and policy',
            'category' => 'leave',
            'chart_type' => 'bar',
            'chart_type_label' => 'Density Heatmap',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'leave_balance_by_employee_policy' => [
            'label' => 'Leave Balance Change by Employee-Policy Pair',
            'description' => 'Top employee-policy pairs by balance change',
            'category' => 'leave',
            'chart_type' => 'bar',
            'chart_type_label' => 'Box Plot',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'leave_balance_change_by_type_department' => [
            'label' => 'Count of Employees by Balance Change Type and Department',
            'description' => 'Employees grouped by balance change type and department',
            'category' => 'leave',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'leave_by_status' => [
            'label' => 'Leave Requests by Status',
            'description' => 'Leave requests overlapping the selected period',
            'category' => 'leave',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],

        // Attendance
        'hours_worked_by_department' => [
            'label' => 'Hours Worked by Department',
            'description' => 'Total hours worked grouped by department',
            'category' => 'attendance',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'hours_worked_by_person' => [
            'label' => 'Hours Worked by Person',
            'description' => 'Total hours worked by employee',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Bar Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'average_status_by_department' => [
            'label' => 'Average Status by Department',
            'description' => 'Present vs absent ratio by department',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'hours_worked_distribution_by_shift' => [
            'label' => 'Hours Worked Distribution by Shift',
            'description' => 'Hours worked grouped by shift',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Box Plot',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'hours_worked_by_date_by_person' => [
            'label' => 'Hours Worked by Date by Person',
            'description' => 'Daily hours trend for the selected period',
            'category' => 'attendance',
            'chart_type' => 'line',
            'chart_type_label' => 'Line Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'hours_worked_trend_by_person' => [
            'label' => 'Hours Worked Trend by Person',
            'description' => 'Hours worked trend by employee',
            'category' => 'attendance',
            'chart_type' => 'line',
            'chart_type_label' => 'Density Heatmap',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'hours_worked_trend_by_department' => [
            'label' => 'Hours Worked Trend by Department',
            'description' => 'Hours worked trend by department',
            'category' => 'attendance',
            'chart_type' => 'line',
            'chart_type_label' => 'Density Heatmap',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'hours_worked_trend_by_designation' => [
            'label' => 'Hours Worked Trend by Designation',
            'description' => 'Hours worked trend by designation',
            'category' => 'attendance',
            'chart_type' => 'line',
            'chart_type_label' => 'Density Heatmap',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'regularization_requests_by_employee' => [
            'label' => 'Total Regularization Requests by Employee',
            'description' => 'Regularization request count by employee',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Bar Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'regularization_requests_vs_days' => [
            'label' => 'Number of Requests vs Number of Days Requested',
            'description' => 'Regularization requests compared to days requested',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Scatter Plot',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'regularization_days_by_department' => [
            'label' => 'Number of Days Requested by Department',
            'description' => 'Regularization days grouped by department',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'regularization_days_by_designation' => [
            'label' => 'Number of Days Requested by Designation',
            'description' => 'Regularization days grouped by designation',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'attendance_status' => [
            'label' => 'Attendance Overview',
            'description' => 'Present, on leave, and absent counts for the selected period',
            'category' => 'attendance',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],

        // Salary
        'total_salary_by_department' => [
            'label' => 'Total Salary By Department',
            'description' => 'Sum of annual CTC by department',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'average_salary_by_department' => [
            'label' => 'Average Salary By Department',
            'description' => 'Average annual CTC by department',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'max_salary_by_department' => [
            'label' => 'Max Salary By Department',
            'description' => 'Maximum annual CTC by department',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'salary_distribution_by_department' => [
            'label' => 'Salary Distribution By Department',
            'description' => 'Salary distribution summary by department',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Box Plot',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'salary_distribution_by_department_gender' => [
            'label' => 'Salary Distribution By Department By Gender',
            'description' => 'Average salary by department and gender',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Box Plot',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'total_salary_by_work_location' => [
            'label' => 'Total Salary By Work Location',
            'description' => 'Sum of annual CTC by work location',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'average_salary_by_work_location' => [
            'label' => 'Average Salary By Work Location',
            'description' => 'Average annual CTC by work location',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'max_salary_by_work_location' => [
            'label' => 'Max Salary By Work Location',
            'description' => 'Maximum annual CTC by work location',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'salary_distribution_by_work_location' => [
            'label' => 'Salary Distribution By Work Location',
            'description' => 'Salary distribution summary by work location',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Box Plot',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'salary_distribution_by_work_location_gender' => [
            'label' => 'Salary Distribution By Work Location By Gender',
            'description' => 'Average salary by work location and gender',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Box Plot',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'salary_breakdown_by_department' => [
            'label' => 'Salary Breakdown By Department',
            'description' => 'Share of total salary by department',
            'category' => 'salary',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'salary_breakdown_by_work_location' => [
            'label' => 'Salary Breakdown By Work Location',
            'description' => 'Share of total salary by work location',
            'category' => 'salary',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'ctc_vs_tenure_heatmap' => [
            'label' => 'CTC vs Tenure Heatmap',
            'description' => 'Average CTC by tenure bands',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Density Heatmap',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],
        'age_vs_ctc_by_department' => [
            'label' => 'Age vs CTC by Department',
            'description' => 'Average CTC by department',
            'category' => 'salary',
            'chart_type' => 'bar',
            'chart_type_label' => 'Scatter Plot',
            'uses_date_range' => false,
            'permission' => 'payroll.manage',
        ],

        // Expense
        'approved_expenses_by_department' => [
            'label' => 'Approved Expenses by Department',
            'description' => 'Approved expense totals grouped by department',
            'category' => 'expense',
            'chart_type' => 'bar',
            'chart_type_label' => 'Bar Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'expense_approval_ratio_by_employee' => [
            'label' => 'Expense Approval Ratio per Employee',
            'description' => 'Approved vs submitted expenses by employee',
            'category' => 'expense',
            'chart_type' => 'bar',
            'chart_type_label' => 'Scatter Plot',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],
        'reimbursement_status_analysis' => [
            'label' => 'Reimbursement Status Analysis',
            'description' => 'Expense reimbursement status breakdown',
            'category' => 'expense',
            'chart_type' => 'donut',
            'chart_type_label' => 'Sunburst Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
        ],

        // Employee self-service charts
        'my_attendance_overview' => [
            'label' => 'My Attendance Overview',
            'description' => 'Your present, leave, and absent days for the selected period',
            'category' => 'attendance',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['employee'],
        ],
        'my_leave_by_status' => [
            'label' => 'My Leave Requests by Status',
            'description' => 'Your leave requests overlapping the selected period',
            'category' => 'leave',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['employee'],
        ],
        'my_hours_by_date' => [
            'label' => 'My Hours Worked by Date',
            'description' => 'Your logged hours across the selected period',
            'category' => 'attendance',
            'chart_type' => 'line',
            'chart_type_label' => 'Line Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['employee'],
        ],
        'my_expense_by_status' => [
            'label' => 'My Expenses by Status',
            'description' => 'Your expense claims in the selected period',
            'category' => 'expense',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['employee'],
        ],
        'my_regularization_by_status' => [
            'label' => 'My Regularization Requests',
            'description' => 'Your attendance regularization requests by status',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Bar Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['employee'],
        ],

        // Team lead / manager charts
        'team_attendance_overview' => [
            'label' => 'Team Attendance Overview',
            'description' => 'Present, leave, and absent days for your team in the selected period',
            'category' => 'attendance',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['team_lead', 'department_head'],
        ],
        'team_leave_by_status' => [
            'label' => 'Team Leave Requests by Status',
            'description' => 'Leave requests for your team in the selected period',
            'category' => 'leave',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['team_lead', 'department_head'],
        ],
        'team_hours_by_person' => [
            'label' => 'Team Hours Worked by Person',
            'description' => 'Total hours logged by each team member',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Bar Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['team_lead', 'department_head'],
        ],
        'team_attendance_trend' => [
            'label' => 'Team Attendance Trend',
            'description' => 'Daily present count for your team across the period',
            'category' => 'attendance',
            'chart_type' => 'line',
            'chart_type_label' => 'Line Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['team_lead', 'department_head'],
        ],
        'team_pending_approvals' => [
            'label' => 'Pending Team Approvals',
            'description' => 'Requests awaiting your review, grouped by type',
            'category' => 'leave',
            'chart_type' => 'bar',
            'chart_type_label' => 'Bar Chart',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
            'audiences' => ['team_lead', 'department_head'],
        ],
        'team_regularization_by_employee' => [
            'label' => 'Team Regularization by Employee',
            'description' => 'Regularization requests submitted by your team',
            'category' => 'attendance',
            'chart_type' => 'bar',
            'chart_type_label' => 'Bar Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['team_lead', 'department_head'],
        ],
        'team_expense_by_status' => [
            'label' => 'Team Expenses by Status',
            'description' => 'Expense claims from your team in the selected period',
            'category' => 'expense',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'uses_date_range' => true,
            'permission' => 'home.dashboard.view',
            'audiences' => ['team_lead', 'department_head'],
        ],

        // Legacy / utility widgets kept for existing saved layouts
        'employees_by_status' => [
            'label' => 'Employees by Status',
            'description' => 'Active and inactive employee headcount',
            'chart_type' => 'donut',
            'chart_type_label' => 'Pie Chart',
            'category' => 'people',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
            'hidden_from_gallery' => true,
        ],
        'employees_by_department' => [
            'label' => 'Employees by Department',
            'description' => 'Headcount grouped by department',
            'chart_type' => 'bar',
            'chart_type_label' => 'Histogram',
            'category' => 'people',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
            'hidden_from_gallery' => true,
        ],
        'pending_requests' => [
            'label' => 'Pending Requests',
            'description' => 'Requests awaiting your review',
            'chart_type' => 'bar',
            'chart_type_label' => 'Bar Chart',
            'category' => 'requests',
            'uses_date_range' => false,
            'permission' => 'home.dashboard.view',
            'hidden_from_gallery' => true,
        ],
    ],
];
